# 服务配置
server:
  port: 8123
  servlet:
    # 设置应用的根路径为/api，所有接口请求都需要加上/api前缀
    context-path: /api

# AI配置
spring:
  application:
    name: my-ai-agent
  ai:
    dashscope:
      api-key: xxx
      chat:
        options:
          model: deepseek-ai/DeepSeek-R1-0528-Qwen3-8B
    openai:
      # 硅基流动API接口
      base-url: https://api.siliconflow.cn
      # api-key 密匙放到环境变量
      api-key: ${openai_api_key}
      chat:
        options:
          # 模型名称(注意使用场景，这里是对话场景)
          model: deepseek-ai/DeepSeek-R1-0528-Qwen3-8B

# 接口文档配置, 访问 http://localhost:8123/api/doc.html
# https://doc.xiaominfo.com/docs/quick-start#spring-boot-3
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.myaiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
